lmu.api.base-url=http://[::1]:6397

# GAP em segundos (Ex: 1.5) para ativar os alertas de pressao e ataque. 
# Use 0 para ignorar o filtro de gap
nlt.overlay.gap-threshold=0
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false